### PR TITLE
Add store path to cabal-cache sync

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by hasufell** [comment]
Still doesn't work on windows: https://github.com/haskell/ghcup-hs/actions/runs/3658670103/jobs/6184264267#step:10:20724

I tried both the form `cabal_store_path="/c/cabal"` and `cabal_store_path="C:\\cabal"`. Both does not work. `cabal help user-config` prints `C:\cabal\config`.

**Comment by newhoggy** [comment]
I wonder if it's because something in `C:\cabal\config` causes the store to be somewhere else?

**Comment by hasufell** [comment]
Doesn't look like it:

```
runneradmin@fv-az89-413 MINGW64 /d/a/ghcup-hs/ghcup-hs
# grep store /c/cabal/config
-- store-dir:

runneradmin@fv-az89-413 MINGW64 /d/a/ghcup-hs/ghcup-hs
# ls /c/cabal/store/
ghc-8.10.7
```

**Comment by hasufell** [comment]
The only thing that makes it work is this:

```sh
		rm -rf /c/Users/runneradmin/AppData/Roaming/cabal
		ln -sf /c/cabal /c/Users/runneradmin/AppData/Roaming/cabal
```

**Comment by hasufell** [comment]
But then it doesn't pick up the cache and rebuilds everything.

**Comment by hasufell** [comment]
So the only way to fix it was to set the cabal store dir to the default `$APPDATA/cabal`. Everything else failed.

I also uploaded more binaries: https://downloads.haskell.org/~ghcup/unofficial-bindists/cabal-cache/1.0.5.1/

**Pull request closed without merging**
