### PR TITLE
Add my GPG keys to the docs

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Comment by hasufell** [comment]
Ben did not upload his cross signed pubkey: https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0x2de04d4e97db64ad

And neither did you: https://keyserver.ubuntu.com/pks/lookup?search=88B57FCF7DB53B4DB3BFA4B1588764FBE22D19C4&fingerprint=on&op=index

And none of you sent me my cross signed pubkey.

I sent both of you an email with the instructions.

**Comment by wz1000** [comment]
I have signed your key: https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xCCC85C0E40C06A8C

**Comment by bgamari** [comment]
> Ben did not upload his cross signed pubkey:

I was not aware that this was necessary. 

> And none of you sent me my cross signed pubkey.
> 
> I sent both of you an email with the instructions.

Strangely, I have not received any email. Nevertheless, I have signed your key and uploaded the signature to `keyserver.ubuntu.com`.

**Comment by hasufell** [comment]
It was sent to both your well-typed address. 🤔

**Comment by wz1000** [comment]
You can see my signature of your key on https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xCCC85C0E40C06A8C (highlighted)


2023-08-25-163331_grab

We don't need to send keys around via email, the following commands should be enough for you to sign my key:

```bash
$ gpg --recv-keys 88B57FCF7DB53B4DB3BFA4B1588764FBE22D19C4
$ gpg --sign-key 88B57FCF7DB53B4DB3BFA4B1588764FBE22D19C4
$ gpg --send-keys 88B57FCF7DB53B4DB3BFA4B1588764FBE22D19C4
```

**Comment by bgamari** [comment]
Likewise, you can see my signature on your key here: https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xCCC85C0E40C06A8C (signing key 2de04d4e97db64ad).

**Pull request merged**
