### PR TITLE
Ansi tui

### LINKED ISSUE #208: TUI on windows
In GitLab by @maerwald on Jul 30, 2021, 03:26

brick doesn't work on windows. What are our options?

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #208 

----

Screenshot_2022-12-06_23-27-51

### CODE REVIEW

**Comment by hasufell** [comment]
I got some preliminary scrolling working that works for resizing and when the window is smaller than the list. It behaves a little different than brick, but I guess it's good enough.

The next thing is figuring out how to execute IO actions, because the `gLogicFunction` of ansi-terminal-game is not monadic. That seems like a major limitation.

**Comment by ffaf1** [comment]
What would be an appropriate signature of `gLogicFunction` for your use case? Maybe I can modify it accordingly.

**Comment by hasufell** [comment]
On second thought maybe:

```hs
data GameT m s =
        Game { gTPS           :: TPS,
               gInitState     :: s,
               gLogicFunction :: GEnv -> s -> Event -> m s,
               gDrawFunction  :: GEnv -> s -> Plane,
               gQuitFunction  :: s -> Bool
               }

type Game = GameT IO

playGame :: Game s -> IO ()
playGame g = () <$ runGIO (runGameGeneral g)

playGameT  :: (forall a . m a -> IO a) -> GameT m s -> IO ()
playGameT trans g = ...
```

**Comment by ffaf1** [comment]
!! That is quite useful! Let me read the patch with care.

**Comment by hasufell** [comment]
The ansi tui is very slow and sluggish, even on linux. I'm not sure it's really a viable option after all. A GTK+ gui may be more interesting, but I'm not sure how that can be sensibly shipped.

**Comment by hasufell** [comment]
@ffaf1 did you have a chance to test the code and observe the performance issues?

**Comment by ffaf1** [comment]
Sorry, I haven’t yet. I put that on my agenda and will report back as soon as I do it!

**Comment by ffaf1** [comment]
I am still in deep waters with other stuff I want to complete first (cabal check). This will take some time!

Il 05 gennaio 2023 alle 16:00 Julian Ospald ha scritto:

**Comment by ffaf1** [comment]
I am finished with cabal, is there a specific commit I should look at?

**Comment by hasufell** [comment]
> I am finished with cabal, is there a specific commit I should look at?

All of it.

**Comment by ffaf1** [comment]
I have built it on Debian Linux and tried it

https://asciinema.org/a/szolXLyG59MIhWf7Z1fWqgcLD

It does not feel sluggish to me. Is there a specific operation which slows it down?

**Comment by ffaf1** [comment]
Note to self, these are the IO actions ghcup performs

```
logicFun _ gs (KeyPress 'i') = do
  bs <- withIOAction install' gs
  pure bs { appRestart = True }
logicFun _ gs (KeyPress 'u') = do
  bs <- withIOAction del' gs
  pure bs { appRestart = True }
logicFun _ gs (KeyPress 's') = do
  bs <- withIOAction set' gs
  pure bs { appRestart = True }
logicFun _ gs (KeyPress 'c') = do
  bs <- withIOAction changelog' gs
  pure bs { appRestart = True }
```

The end result is most of the time ``m (Either String ())``. Maybe they can be interleaved between various `playGame` invocations.

**Comment by hasufell** [comment]
Brick supports windows now. This is no longer needed.

**Pull request closed without merging**
