### PR TITLE
Implement support for nightlies, wrt #824

### PR DESCRIPTION
**Pull request by hasufell**
TODO:

* [x] allow to install via date
* [x] suggest alternative nightly date if requested date is missing

### CODE REVIEW

**Comment by david-christiansen** [comment]
Wonderful to see this happening!

**Comment by mpickering** [comment]
I tested this PR with the following commands:

Using this prefix: 

```
ghcup --url-source https://ghc.gitlab.haskell.org/ghcup-metadata/ghcup-nightlies-0.0.7.yaml 
```

Installing a non-latest nightly build, works.

```
install ghc- 9.7.20230526
```

Installing the latest nightly build, works.

```
install ghc-9.7.20230527
```

Looking at the display in the tui, displays the LatestNightly (but no other nightly builds, pressing "toggle all versions" doesn't do anything).

```
tui
```

Listing releases does not list nightly releases

```
> list
   Tool  Version  Tags Notes
✔✔ ghcup 0.1.19.2      stray

```

Using the `--show-nightly` flag they are displayed.

```
   Tool  Version      Tags           Notes     
✗  ghc   9.7.20230526 nightly        2023-03-27
✗  ghc   9.7.20230527 latest-nightly 2023-03-28
✔✔ ghcup 0.1.19.2                    stray
```

**Comment by mpickering** [comment]
Perhaps it would be good for you to test this yourself @hasufell but it seems like things are completed from the GHC side.

**Comment by hasufell** [comment]
@mpickering 

1. dates look incorrect (the month)
2. some nightlies have duplicated tag

```
✗  ghc   9.7.20230526 nightly,nightly 2023-03-27
✗  ghc   9.7.20230527 nightly,nightly 2023-03-28
✗  ghc   9.7.20230601 nightly,nightly 2023-03-02
✗  ghc   9.7.20230602 nightly,nightly 2023-03-03
✗  ghc   9.7.20230603 nightly         2023-03-04
✗  ghc   9.7.20230605 nightly         2023-03-06
✗  ghc   9.7.20230606 nightly         2023-03-07
✗  ghc   9.7.20230607 nightly         2023-03-08
✗  ghc   9.7.20230610 nightly         2023-03-12
✗  ghc   9.7.20230613 nightly         2023-03-14
✗  ghc   9.7.20230614 nightly         2023-03-15
✗  ghc   9.7.20230615 nightly         2023-03-16
✗  ghc   9.7.20230616 nightly         2023-03-17
✗  ghc   9.7.20230617 nightly         2023-03-18
✗  ghc   9.7.20230618 nightly         2023-03-19
✗  ghc   9.7.20230619 latest-nightly  2023-03-20
```

**Comment by mpickering** [comment]
> @mpickering
> 
>     1. dates look incorrect (the month)
> 
>     2. some nightlies have duplicated tag
> 
> 
> ```
> ✗  ghc   9.7.20230526 nightly,nightly 2023-03-27
> ✗  ghc   9.7.20230527 nightly,nightly 2023-03-28
> ✗  ghc   9.7.20230601 nightly,nightly 2023-03-02
> ✗  ghc   9.7.20230602 nightly,nightly 2023-03-03
> ✗  ghc   9.7.20230603 nightly         2023-03-04
> ✗  ghc   9.7.20230605 nightly         2023-03-06
> ✗  ghc   9.7.20230606 nightly         2023-03-07
> ✗  ghc   9.7.20230607 nightly         2023-03-08
> ✗  ghc   9.7.20230610 nightly         2023-03-12
> ✗  ghc   9.7.20230613 nightly         2023-03-14
> ✗  ghc   9.7.20230614 nightly         2023-03-15
> ✗  ghc   9.7.20230615 nightly         2023-03-16
> ✗  ghc   9.7.20230616 nightly         2023-03-17
> ✗  ghc   9.7.20230617 nightly         2023-03-18
> ✗  ghc   9.7.20230618 nightly         2023-03-19
> ✗  ghc   9.7.20230619 latest-nightly  2023-03-20
> ```

Thanks, see https://gitlab.haskell.org/ghc/ghc/-/issues/23552

**Comment by mpickering** [comment]
I pushed a manual update to remove the duplicate tags, I should have fixed that already on master. (https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10591)

**Comment by hasufell** [comment]
@mpickering the `viReleaseDay` is still incorrect

**Pull request merged**
