### PR TITLE
Bump for brick windows

### PR DESCRIPTION
**Pull request by hasufell**
ghcup_windows_brick

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Just a word of caution: we discovered some issues in vty-windows that got fixed and some that are still being investigated. Please make sure you test well and use the latest vty-windows release!

**Comment by hasufell** [comment]
> and some that are still being investigated

Can you let us know what this is?

**Comment by hasufell** [comment]
I noticed that I can't do anything during `suspendAndResume`. It seems all input is ignored.

**Comment by jtdaugherty** [comment]
@hasufell I was thinking of the discussion at https://github.com/chhackett/vty-windows/issues/10 - although those have largely been fixed at this point.

Is the `suspendAndResume` misbehavior happening on Windows?

**Comment by chhackett** [comment]
> > and some that are still being investigated
> 
> Can you let us know what this is?

@hasufell 
Hello,
I uploaded a patch today that fixes the remaining weird artifact issues in Powershell and cmd windows.

There is still one issue with colors getting rendered incorrectly in Powershell only. 
https://github.com/chhackett/vty-windows/issues/13

**Comment by hasufell** [comment]
> Is the suspendAndResume misbehavior happening on Windows?

Yeah, but I think it's fixed now.

**Comment by jtdaugherty** [comment]
> Yeah, but I think it's fixed now.

That doesn't sound good. (As in, perhaps it doesn't work some of the time due to a race or something.) There could be something amiss in the Windows shutdown/startup code that needs to be adjusted..

**Comment by hasufell** [comment]
> > Yeah, but I think it's fixed now.
> 
> That doesn't sound good. (As in, perhaps it doesn't work some of the time due to a race or something.) There could be something amiss in the Windows shutdown/startup code that needs to be adjusted..

I think the only way is to put it out there. I can't reproduce properly.

**Pull request merged**
