### PR TITLE
Add multi-user install support in windows bootstrap

### PR DESCRIPTION
**Pull request by dfordivam**
By setting up the env vars at the "Machine" level.

If there are other users currently logged in, they will have to sign out and login again for the global env vars to take effect.

### CODE REVIEW

**Comment by dfordivam** [comment]
The cabal config adjustments didn't happen with this. Those will have to be done manually by each user.

**Comment by hasufell** [comment]
Hmm... do they have to run the script as administrator or will windows create a popup for privilege escalation?

**Comment by dfordivam** [comment]
So this enhancement is a relatively minor convenience over manual env vars adjustments. And changing the system wide PATH via this script with admin privilege is also slightly scary.
I suggest we ditch this idea and only provide instructions in guide for manual setup of env vars.

**Comment by hasufell** [comment]
Agreed

**Pull request closed without merging**
