### PR TITLE
Set LD=ld.bfd on Alpine linux during bindist configure

### LINKED ISSUE #967: Default to `ld.bfd` for bindist configure (alpine or all linux?)
GHC likes to pick `ld.gold`. However, experience shows that it's more buggy and unreliable, e.g. https://gitlab.haskell.org/ghc/ghc/-/issues/17508

GHCup strives to give users a configuration that works reliably, not optimize for compilation speed and risk segfaults.

The idea would be to do the following on Alpine or even all Linuxes:

* check if there's a `ld.bfd` binary present
* check if `LD` environment variable is not set
* if both is true, pass `LD=ld.bfd` to the environment executing the bindist configure script

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #967

### CODE REVIEW

**Review by runeksvendsen — COMMENTED** [review]
How much work would it be to test in CI that this fixes the segfault issue?

**Comment by runeksvendsen** [comment]
This also fixes https://github.com/haskell/ghcup-hs/issues/962, right?

**Comment by hasufell** [comment]
> This also fixes #962, right?

No, it unfortunately doesn't. I'm suspecting an actual bug in 9.4.8 series.

**Comment by hasufell** [comment]
> How much work would it be to test in CI that this fixes the segfault issue?

I don't feel that's gonna add much.

We have evidence here:

* https://gitlab.haskell.org/ghc/ghc/-/issues/17508#note_313450
* https://sourceware.org/bugzilla/show_bug.cgi?id=23856

The minimal reproducer (C code) is shown here (and still works): https://gitlab.haskell.org/ghc/ghc/-/issues/17508#note_372662

There's no minimal reproducer for Haskell.

My past days as Gentoo distributor also remind me that ld.gold was always more problematic, so I don't think it's a good default to begin with.

**Comment by hasufell** [comment]
> There's no minimal reproducer for Haskell.

Ah, silly me... I didn't edit the settings file correctly.

Obviously, this works:

```
$ cat Foo.hs
main = putStrLn "hello world"
ghc Foo.hs
./Foo
Segmentation fault (core dumped)
```

Then make sure you ghc settings file has these lines:

```
,("C compiler link flags", "-fuse-ld=gold")
,("ld command", "ld.gold")
,("Merge objects command", "ld.gold")
```

**Review by runeksvendsen — COMMENTED** [review]
The way I read the code, we previously ran the configure script with an empty environment — ie. it did not inherit anything from the environment of GHCup. Is this correctly understood?

If this is the case then I'm not convinced that we should pass all of GHCup's environment plus `LD=ld.bfd` to the configure script in the positive case. In that case why not use an environment with only `LD=ld.bfd`?

**Comment by runeksvendsen** [comment]
> > we previously ran the configure script with an empty environment — ie. it did not inherit anything from the environment of GHCup. Is this correctly understood?
> 
> No, that's not correct. That parameter overwrites the current environment for the subprocess. `LD=ld.bfd ghcup install ghc ...` works perfectly fine.

So passing `Just [("LD", "ld.bfd")]` as the last argument to `execLogged` will execute the process in the same environment as that of GHCup but with the LD env var overwritten?

If that's the case then why do we need

```
(("LD", "ld.bfd") : cEnv)
```

instead of just

```
[("LD", "ld.bfd")]
```

?

**Comment by hasufell** [comment]
> So passing Just [("LD", "ld.bfd")] as the last argument to execLogged will execute the process in the same environment as that of GHCup but with the LD env var overwritten?

No, you pass the entire environment.

**Comment by runeksvendsen** [comment]
Okay I understand now. I thought passing `Nothing` as the environment means the executed process would have an empty environment. But `Nothing` means "inherit environment of the parent process" whereas `Just []` means "use an empty environment".

**Review by runeksvendsen — APPROVED** [review]
The code looks good to me. But I don't have a way to test it, so I will leave that up to you.

**Pull request merged**
