### PR TITLE
Debug issue #962

### PR DESCRIPTION
**Pull request by runeksvendsen**

### CODE REVIEW

**Comment by hasufell** [comment]
I think it's easier to test this locally in a docker container than dealing with CI.

**Comment by hasufell** [comment]
I think it's easier to test this locally in a docker container than dealing with CI.

**Comment by runeksvendsen** [comment]
> I think it's easier to test this locally in a docker container than dealing with CI.

Initially it was much easier for me to fire off some CI runs given that I have no way of easily executing GH Actions locally.

**Comment by dfordivam** [comment]
The issue had been debugged.

**Pull request closed without merging**
